### ISSUE TITLE
 とくしまOSS勉強会　Ruby集中講座１　やることリスト

### ISSUE THREAD

**Issue by sunny4381** [tokushimarb/tokushimarb.github.io#3]
## 概要

[とくしまOSS勉強会　Ruby集中講座１](https://www.e-tetsuzuki99.com/eap-jportal/PkgNaviDetail.do?lcd=360007&pkgSeq=214093)のやることリストです。

現時点でまだ机上の空論的に列挙していることですので，質問や不明瞭な点が出てくると思います．
その際には付け足していってください．
### @kaosf
- [x] スライド
- [x] コードを全部
- [x] コマンドを全部
### @sunny4381
- [x] VirtualBoxとVagrantのインストール用のファイル
- [x] 使用するUSBフラッシュメモリ等の手配 (私も2,3点であれば用意出来ます)
- [x] Vagrantfile用意
- [x] CentOSで用意する(CentOSのバージョンの選定は任せます)
- [x] `ruby -v`と`gem -v`が実行出来る状態が目標
- [x] teratermやPuTTYも一応用意(ファイルをコピーすれば使える状態)(設定するべき項目(UTF-8に変更するなど)も思いつく範囲で列挙して下さい)
## 参考

[開発者のタスク管理をGitHubで行ったらうまくいった話](http://dev.classmethod.jp/tool/git/github-issue-driven-dev/)
[募集・申し込みページ](https://www.e-tetsuzuki99.com/eap-jportal/PkgNaviDetail.do?lcd=360007&pkgSeq=214093)
[Facebookページ](https://www.facebook.com/events/1440692922904618/)

**Comment by kaosf** [comment]
:+1:

そういえばチェックリスト作れるんでしたね！(余談ですけど，ほんとこの仕組みを実装してるの凄いと思う…)

**Comment by kaosf** [comment]
Assigneeは複数人設定出来ないのか…

**Comment by sunny4381** [comment]
徳島 Free Wi-Fi とくぎんトモニプラザ
http://tokushima-wifi.jp/docs/240.html

**Comment by sunny4381** [comment]
Vagrant の準備できました。
https://github.com/tokushimarb/ruby-vagrant

最低限のパッケージと、最低限の gem しか入れてません。
もし、入れておいた方がいい gem があったら、連絡ください。

**Comment by sunny4381** [comment]
Mac の VirtualBox に Windows 10 TP をインストールし、
Windows 10 TP に VirtualBox と Vagrant をインストールして試してみました。
64ビット版 Vagrant Box はハードウェアの支援が受けられないようで動作しませんでしたが、
32ビット版 Vagrant Box は問題なかったです。

**Comment by sunny4381** [comment]
今朝方チェックした時は、Vagrant 1.7.2（→ VirtualBox 5.0 未サポート）だったのが、
今確認すると Vagrant 1.7.3（→VirtualBox 5.0 対応）がリリースされていました。

しかし、今回の勉強会は、VirtualBox 4.3 / Vagrant 1.7.2 で対応したいと思います。

**Comment by kaosf** [comment]
> 最低限のgem

https://github.com/tokushimarb/ruby-vagrant/blob/master/packer/scripts/bundler.sh

bundlerだけですね．了解です．

**Comment by kaosf** [comment]
> 今回の勉強会は、VirtualBox 4.3 / Vagrant 1.7.2 で対応

了解です．最先端(VirtualBox 5.0)でなくても良いと思います．

**Comment by sunny4381** [comment]
USB メモリー 3 つ確保。
テキストエディタとして Atom も入れました。

**Comment by kaosf** [comment]
でけた

https://github.com/kaosf/20150731-oss-ruby

http://kaosf.github.io/20150731-oss-ruby
